#
# Copyright (c) 2021-2022 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#
FROM openjdk:11-jre-slim-buster

ENV JAVA_TOOL_OPTIONS ""
ENV FUSEKI_CONFIG agent.ttl
ENV FUSEKI_PORT 8082

WORKDIR /app
COPY jena/jena-fuseki2/jena-fuseki-server/target/jena-fuseki-server-4.4.0.jar fuseki.jar

EXPOSE 8082

ENTRYPOINT java \
    -classpath fuseki.jar \
    org.apache.jena.fuseki.main.cmds.FusekiMainCmd \
    --config ${FUSEKI_CONFIG} --port ${FUSEKI_PORT} --auth=basic
