#
# Copyright (c) 2021-2022 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#
FROM openjdk:11-jre-slim-buster

ENV JAVA_TOOL_OPTIONS ""
ENV FUSEKI_CONFIG agent.ttl
ENV FUSEKI_PORT 8082

COPY jena/jena-fuseki2/jena-fuseki-server/target/jena-fuseki-server-4.4.0.jar /app/fuseki.jar

# Security issue A1SLDT-828
RUN groupadd -g 30000 fuseki && \
    useradd -u 10000 -g fuseki -ms /bin/sh fuseki && \
    chown -R fuseki:fuseki /app

USER fuseki
WORKDIR /app
EXPOSE 8082

ENTRYPOINT java \
    -classpath fuseki.jar \
    org.apache.jena.fuseki.main.cmds.FusekiMainCmd \
    --config ${FUSEKI_CONFIG} --port ${FUSEKI_PORT} --auth=basic
