{{- range $dataplane_name, $dataplane := .Values.repositories }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "txdc.fullname" . }}-{{- $dataplane.name }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "txdc.dataplane.labels" . | nindent 4 }}
data:
  opentelemetry.properties: |-
    {{- $dataplane.opentelemetry | nindent 4 }}

  logging.properties: |-
    {{- $dataplane.logging | nindent 4 }}

  {{- range $config_name, $config_value := $dataplane.configs }}
  {{- $config_name }}: |-
  {{- $config_value | nindent 4 }}
  {{- end }}

  {{- end }}

{{- end }}
