#
#  Copyright (c) 2023 ZF Friedrichshafen AG
#  Copyright (c) 2023 Mercedes-Benz Tech Innovation GmbH
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#  Copyright (c) 2023 T-Systems International GmbH
#  Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#

{{- range $dataplane_name, $dataplane := .Values.repositories }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "txdc.fullname" . }}-{{ $dataplane.name }}
  labels:
    {{- include "txdc.dataplane.labels" . | nindent 4 }}
spec:
  {{- if not $dataplane.autoscaling.enabled }}
  replicas: {{ $dataplane.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "txdc.dataplane.selectorLabels" $dataplane | nindent 6 }}
  template:
    metadata:
      {{- with $dataplane.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "txdc.dataplane.selectorLabels" $dataplane | nindent 8 }}
        {{- with $dataplane.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "txdc.serviceAccountName" . }}
      securityContext:
        {{- toYaml $dataplane.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml $dataplane.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml $dataplane.securityContext | nindent 12 }}
          {{- if $dataplane.image.repository }}
          image: "{{ $dataplane.image.repository }}:{{ $dataplane.image.tag | default .Chart.AppVersion }}"
          {{- else if and .Values.vault.hashicorp }}
          image: "ghcr.io/catenax-ng/product-agents-edc/dataplane-hashicorp:{{ $dataplane.image.tag | default .Chart.AppVersion }}"
          {{- else if .Values.vault.azure }}
          image: "ghcr.io/catenax-ng/product-agents-edc/dataplane-azure-vault:{{ $dataplane.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          {{- fail "cannot choose data-plane image automatically based on configuration" }}
          {{- end }}
          imagePullPolicy: {{ $dataplane.image.pullPolicy }}
          ports:
          {{- range $key,$value := $dataplane.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if $dataplane.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $dataplane.endpoints.observability.path }}/check/liveness
              port: {{ $dataplane.endpoints.observability.port }}
            initialDelaySeconds: {{ $dataplane.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $dataplane.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $dataplane.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ $dataplane.livenessProbe.failureThreshold }}
            successThreshold: {{ $dataplane.livenessProbe.successThreshold }}
          {{- end }}
          {{- if $dataplane.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $dataplane.endpoints.observability.path }}/check/readiness
              port: {{ $dataplane.endpoints.observability.port }}
            initialDelaySeconds: {{ $dataplane.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $dataplane.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $dataplane.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ $dataplane.readinessProbe.failureThreshold }}
            successThreshold: {{ $dataplane.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml $dataplane.resources | nindent 12 }}
          env:
          {{- if $dataplane.debug.enabled }}
            - name: "JAVA_TOOL_OPTIONS"
            {{- if and $dataplane.debug.enabled $dataplane.debug.suspendOnStart }}
              value: >-
                {{ printf "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=%v" $dataplane.debug.port }}
            {{- else }}
              value: >-
                {{ printf "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=%v" $dataplane.debug.port }}
            {{- end }}
          {{- end }}

            #######
            # API #
            #######
            - name: "WEB_HTTP_DEFAULT_PORT"
              value: {{ $dataplane.endpoints.default.port | quote }}
            - name: "WEB_HTTP_DEFAULT_PATH"
              value: {{ $dataplane.endpoints.default.path | quote }}
            - name: "WEB_HTTP_CONTROL_PORT"
              value: {{ $dataplane.endpoints.control.port | quote }}
            - name: "WEB_HTTP_CONTROL_PATH"
              value: {{ $dataplane.endpoints.control.path | quote }}
            - name: "WEB_HTTP_PUBLIC_PORT"
              value: {{ $dataplane.endpoints.public.port | quote }}
            - name: "WEB_HTTP_PUBLIC_PATH"
              value: {{ $dataplane.endpoints.public.path | quote }}
            - name: "EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT"
              value: {{ include "txdc.controlplane.url.validation" .}}
            - name: "WEB_HTTP_OBSERVABILITY_PORT"
              value: {{ $dataplane.endpoints.observability.port | quote }}
            - name: "WEB_HTTP_OBSERVABILITY_PATH"
              value: {{ $dataplane.endpoints.observability.path | quote }}
            - name: "TRACTUSX_API_OBSERVABILITY_ALLOW-INSECURE"
              value: {{ $dataplane.endpoints.observability.insecure | quote }}

          ###################
          # AGENT STUFF     #
          ###################

          {{- if $dataplane.endpoints.callback }}
            - name: "WEB_HTTP_CALLBACK_PORT"
              value: {{ $dataplane.endpoints.callback.port | quote }}
            - name: "WEB_HTTP_CALLBACK_PATH"
              value: {{ $dataplane.endpoints.callback.path | quote }}
            - name: "CX_AGENT_CALLBACK"
              value: {{- printf "http://%s-%s:%v%s/endpoint-data-reference" ( include "txdc.fullname" $ ) $dataplane.name $dataplane.endpoints.callback.port $dataplane.endpoints.callback.path -}}

            - name: "EDC_API_AUTH_KEY"
              value: { { .Values.controlplane.endpoints.management.authKey | required ".Values.controlplane.endpoints.mangement.authKey is required" | quote } }
            - name: "CX_AGENT_CONTROLPLANE_URL"
              value: {{- printf "http://%s-controlplane:%v" ( include "txdc.fullname" $ ) .Values.controlplane.endpoints.ids.port -}}
            - name: "CX_AGENT_CONTROLPLANE_MANAGEMENT"
              value: {{- printf "http://%s-controlplane:%v%s" ( include "txdc.fullname" $ ) .Values.controlplane.endpoints.management.port .Values.controlplane.endpoints.management.path -}}
          {{- end }}

          {{- if $dataplane.agent.default }}
            - name: "CX_AGENT_ASSET_FILE"
              value: {{ join "," $dataplane.agent.default }} 
          {{- end }}
          
          {{- if $dataplane.agent.connectors }}
            - name: "CX_AGENT_DATASPACE_REMOTES"
              value: {{ join "," $dataplane.agent.connectors }} 

            - name: "CX_AGENT_DATASPACE_SYNCHRONIZATION"
              value: {{ $dataplane.agent.synchronization | required (printf ".Values.dataplane.%s.agent.synchronization should be set if connectors are specified" $dataplane_name) }}
          {{- end }}

            #######
            # AWS #
            #######
            {{- if $dataplane.aws.endpointOverride }}
            - name: "EDC_AWS_ENDPOINT_OVERRIDE"
              value: {{ $dataplane.aws.endpointOverride | quote }}
            {{- end   }}
            {{- if $dataplane.aws.secretAccessKey }}
            - name: "AWS_SECRET_ACCESS_KEY"
              value: {{ $dataplane.aws.secretAccessKey | quote }}
            {{- end }}
            {{- if $dataplane.aws.accessKeyId }}
            - name: "AWS_ACCESS_KEY_ID"
              value: {{ $dataplane.aws.accessKeyId | quote }}
            {{- end }}

            ###########
            ## VAULT ##
            ###########

          {{- if .Values.vault.hashicorp.enabled }}
            # see extension https://github.com/eclipse-tractusx/tractusx-edc/tree/main/edc-extensions/hashicorp-vault
            - name: "EDC_VAULT_HASHICORP_URL"
              value: {{ .Values.vault.hashicorp.url | required ".Values.vault.hashicorp.url is required" | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN"
              value: {{ .Values.vault.hashicorp.token | required ".Values.vault.hashicorp.token is required" | quote }}
            - name: "EDC_VAULT_HASHICORP_TIMEOUT_SECONDS"
              value: {{ .Values.vault.hashicorp.timeout | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED"
              value: {{ .Values.vault.hashicorp.healthCheck.enabled | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK"
              value: {{ .Values.vault.hashicorp.healthCheck.standbyOk | quote }}
            - name: "EDC_VAULT_HASHICORP_API_SECRET_PATH"
              value: {{ .Values.vault.hashicorp.paths.secret | quote }}
            - name: "EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH"
              value: {{ .Values.vault.hashicorp.paths.health | quote }}
          {{- end }}

          {{- if .Values.vault.azure.enabled }}
            - name: "EDC_VAULT_CLIENTID"
              value: {{ .Values.vault.azure.client | quote  }}
            - name: "EDC_VAULT_TENANTID"
              value: {{ .Values.vault.azure.tenant | quote }}
            - name: "EDC_VAULT_NAME"
              value: {{ .Values.vault.azure.name | quote }}
            # only set the env var if config value not null
            {{- if .Values.vault.azure.secret }}
            - name: "EDC_VAULT_CLIENTSECRET"
              value: {{ .Values.vault.azure.secret | quote }}
            {{- end }}
            # only set the env var if config value not null
            {{- if .Values.vault.azure.certificate }}
            - name: "EDC_VAULT_CERTIFICATE"
              value: {{ .Values.vault.azure.certificate | quote }}
            {{- end }}
          {{- end }}

            ######################################
            ## Additional environment variables ##
            ######################################
          {{- range $key, $value := $dataplane.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- range $key, $value := $dataplane.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if and (or $dataplane.envSecretNames $dataplane.envConfigMapNames) (or (gt (len $dataplane.envSecretNames) 0) (gt (len $dataplane.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := $dataplane.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := $dataplane.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: "configuration"
              mountPath: "/app/opentelemetry.properties"
              subPath: "opentelemetry.properties"
            - name: "configuration"
              mountPath: "/app/logging.properties"
              subPath: "logging.properties"
      volumes:
        - name: "configuration"
          configMap:
            name: {{ include "txdc.fullname" . }}-{{ $dataplane_name }}
            items:
              - key: "opentelemetry.properties"
                path: "opentelemetry.properties"
              - key: "logging.properties"
                path: "logging.properties"
      {{- with $dataplane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $dataplane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $dataplane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}