#
#  Copyright (c) 2023 T-Systems International GmbH
#  Copyright (c) 2023 ZF Friedrichshafen AG
#  Copyright (c) 2023 Mercedes-Benz Tech Innovation GmbH
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#  Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#
{{ $root := . }}
{{- range $dataplane_name, $dataplane := .Values.dataplanes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "txdc.fullname" $root }}-{{ $dataplane.name }}
  labels:
    {{- include "txdc.dataplane.labels" (dict "dataplane" $dataplane "root" $root) | nindent 4 }}
spec:
  {{- if not $dataplane.autoscaling.enabled }}
  replicas: {{ $dataplane.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "txdc.dataplane.selectorLabels" (dict "dataplane" $dataplane "root" $root) | nindent 6 }}
  template:
    metadata:
      {{- with $dataplane.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "txdc.dataplane.selectorLabels" (dict "dataplane" $dataplane "root" $root) | nindent 8 }}
        {{- with $dataplane.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "txdc.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $dataplane.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml $dataplane.initContainers | nindent 8 }}
      containers:
        - name: {{ $root.Chart.Name }}
          securityContext:
            {{- toYaml $dataplane.securityContext | nindent 12 }}
          {{- if $dataplane.image.repository }}
          image: "{{ $dataplane.image.repository }}:{{ $dataplane.image.tag | default "0.5.0" }}"
          {{- else if $dataplane.agent }}
          image: "ghcr.io/catenax-ng/product-agents-edc/agentplane-hashicorp:{{ $dataplane.image.tag | default $root.Chart.AppVersion }}"
          {{- else }}
          image: "tractusx/edc-dataplane-hashicorp-vault:{{ .Values.dataplane.image.tag | default "0.5.0" }}"
          {{- end }}
          imagePullPolicy: {{ $dataplane.image.pullPolicy }}
          ports:
          {{- range $key,$value := $dataplane.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if $dataplane.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $dataplane.endpoints.default.path }}/check/liveness
              port: {{ $dataplane.endpoints.default.port }}
            initialDelaySeconds: {{ $dataplane.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $dataplane.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $dataplane.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ $dataplane.livenessProbe.failureThreshold }}
            successThreshold: {{ $dataplane.livenessProbe.successThreshold }}
          {{- end }}
          {{- if $dataplane.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $dataplane.endpoints.default.path }}/check/readiness
              port: {{ $dataplane.endpoints.default.port }}
            initialDelaySeconds: {{ $dataplane.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $dataplane.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $dataplane.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ $dataplane.readinessProbe.failureThreshold }}
            successThreshold: {{ $dataplane.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml $dataplane.resources | nindent 12 }}
          env:
          {{- if $dataplane.debug.enabled }}
            - name: "JAVA_TOOL_OPTIONS"
            {{- if and $dataplane.debug.enabled $dataplane.debug.suspendOnStart }}
              value: >-
                {{ printf "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=%v" $dataplane.debug.port }}
            {{- else }}
              value: >-
                {{ printf "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=%v" $dataplane.debug.port }}
            {{- end }}
          {{- end }}

            #######
            # API #
            #######
            - name: "WEB_HTTP_DEFAULT_PORT"
              value: {{ $dataplane.endpoints.default.port | quote }}
            - name: "WEB_HTTP_DEFAULT_PATH"
              value: {{ $dataplane.endpoints.default.path | quote }}
            - name: "WEB_HTTP_CONTROL_PORT"
              value: {{ $dataplane.endpoints.control.port | quote }}
            - name: "WEB_HTTP_CONTROL_PATH"
              value: {{ $dataplane.endpoints.control.path | quote }}
            - name: "WEB_HTTP_PUBLIC_PORT"
              value: {{ $dataplane.endpoints.public.port | quote }}
            - name: "WEB_HTTP_PUBLIC_PATH"
              value: {{ $dataplane.endpoints.public.path | quote }}
            - name: "EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT"
              value: {{ include "txdc.controlplane.url.validation" $root}}

          {{- if $dataplane.endpoints.callback }}
            ###################
            # AGENT CALLBACK  #
            ###################
            - name: "WEB_HTTP_CALLBACK_PORT"
              value: {{ $dataplane.endpoints.callback.port | quote }}
            - name: "WEB_HTTP_CALLBACK_PATH"
              value: {{ $dataplane.endpoints.callback.path | quote }}
            - name: "CX_AGENT_CALLBACK"
              value: {{ printf "http://%s-%s:%v%s/endpoint-data-reference" ( include "txdc.fullname" $root ) $dataplane.name $dataplane.endpoints.callback.port $dataplane.endpoints.callback.path | quote }}
            - name: "EDC_API_AUTH_KEY"
              value: {{ $root.Values.controlplane.endpoints.management.authKey | required ".Values.controlplane.endpoints.mangement.authKey is required" | quote }}
            - name: "EDC_PARTICIPANT_ID"
              value: {{ $root.Values.participant.id | quote }}
            - name: "CX_AGENT_CONTROLPLANE_PROTOCOL"
              value: {{ printf "http://%s-controlplane:%v" ( include "txdc.fullname" $root ) $root.Values.controlplane.endpoints.protocol.port | quote }}
            - name: "CX_AGENT_CONTROLPLANE_MANAGEMENT"
              value: {{ printf "http://%s-controlplane:%v%s%s" ( include "txdc.fullname" $root ) $root.Values.controlplane.endpoints.management.port $root.Values.controlplane.endpoints.management.path "/v2" | quote }}
          {{- end }}

          {{- if $dataplane.agent.default }}
            ###############
            # AGENT INIT  #
            ###############
            - name: "CX_AGENT_ASSET_FILE"
              value: {{ join "," $dataplane.agent.default | quote }} 
            - name: "CX_AGENT_SKILL_CONTRACT_DEFAULT"
              value: {{ $dataplane.agent.skillcontract | quote }}

          {{- end }}
          
          {{- if $dataplane.agent.connectors }}
            ###################
            # AGENT SYNC      #
            ###################
            - name: "CX_AGENT_DATASPACE_REMOTES"
              value: {{ join "," $dataplane.agent.connectors | quote }} 
            - name: "CX_AGENT_DATASPACE_SYNCHRONIZATION"
              value: {{ $dataplane.agent.synchronization | required (printf ".Values.dataplane.%s.agent.synchronization should be set if connectors are specified" $dataplane_name) | quote }}
            - name: "CX_AGENT_FEDERATION_BATCH_MAX"
              value: {{ $dataplane.agent.maxbatchsize | quote }} 
          {{- end }}

            #######
            # AWS #
            #######
            {{- if $dataplane.aws.endpointOverride }}
            - name: "EDC_AWS_ENDPOINT_OVERRIDE"
              value: {{ $dataplane.aws.endpointOverride | quote }}
            {{- end   }}
            {{- if $dataplane.aws.secretAccessKey }}
            - name: "AWS_SECRET_ACCESS_KEY"
              value: {{ $dataplane.aws.secretAccessKey | quote }}
            {{- end }}
            {{- if $dataplane.aws.accessKeyId }}
            - name: "AWS_ACCESS_KEY_ID"
              value: {{ $dataplane.aws.accessKeyId | quote }}
            {{- end }}

            ###############
            ## EDR CACHE ##
            ###############

            # see extension https://github.com/eclipse-tractusx/tractusx-edc/tree/main/edc-extensions/edr-cache-sql
            - name: "EDC_DATASOURCE_EDR_NAME"
              value: "edr"
            - name: "EDC_DATASOURCE_EDR_USER"
              value: {{ $root.Values.postgresql.auth.username | required ".Values.postgresql.auth.username is required" | quote }}
            - name: "EDC_DATASOURCE_EDR_PASSWORD"
              value: {{ $root.Values.postgresql.auth.password | required ".Values.postgresql.auth.password is required" | quote }}
            - name: "EDC_DATASOURCE_EDR_URL"
              value: {{ tpl $root.Values.postgresql.jdbcUrl . | quote }}

            ###########
            ## VAULT ##
            ###########

            # see extension https://github.com/eclipse-tractusx/tractusx-edc/tree/main/edc-extensions/hashicorp-vault
            - name: "EDC_VAULT_HASHICORP_URL"
              value: {{ $root.Values.vault.hashicorp.url | required ".Values.vault.hashicorp.url is required" | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN"
              value: {{ $root.Values.vault.hashicorp.token | required ".Values.vault.hashicorp.token is required" | quote }}
            - name: "EDC_VAULT_HASHICORP_TIMEOUT_SECONDS"
              value: {{ $root.Values.vault.hashicorp.timeout | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED"
              value: {{ $root.Values.vault.hashicorp.healthCheck.enabled | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK"
              value: {{ $root.Values.vault.hashicorp.healthCheck.standbyOk | quote }}
            - name: "EDC_VAULT_HASHICORP_API_SECRET_PATH"
              value: {{ $root.Values.vault.hashicorp.paths.secret | quote }}
            - name: "EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH"
              value: {{ $root.Values.vault.hashicorp.paths.health | quote }}

            ######################################
            ## Additional environment variables ##
            ######################################
            - name: "EDC_CONNECTOR_NAME"
              value: {{ include "txdc.fullname" $root}}-{{ $dataplane.name }}
          {{- range $key, $value := $dataplane.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- range $key, $value := $dataplane.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if and (or $dataplane.envSecretNames $dataplane.envConfigMapNames) (or (gt (len $dataplane.envSecretNames) 0) (gt (len $dataplane.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := $dataplane.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := $dataplane.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: "configuration"
              mountPath: "/app/opentelemetry.properties"
              subPath: "opentelemetry.properties"
            - name: "configuration"
              mountPath: "/app/logging.properties"
              subPath: "logging.properties"
            - name: "tmp"
              mountPath: "/tmp"

            {{- range $config_name, $config_value := $dataplane.configs }}
            - name: "configuration"
              mountPath: {{ printf "/app/%s" $config_name | quote }}
              subPath: {{ printf "%s" $config_name | quote }}
            {{- end }}
      volumes:
        - name: "configuration"
          configMap:
            name: {{ include "txdc.fullname" $root }}-{{ $dataplane_name }}
            items:
              - key: "opentelemetry.properties"
                path: "opentelemetry.properties"
              - key: "logging.properties"
                path: "logging.properties"
            {{- range $config_name, $config_value := $dataplane.configs }}
              - key: {{ printf "%s" $config_name | quote }}
                path: {{ printf "%s" $config_name | quote }}
            {{- end }}
        - name: "tmp"
          emptyDir: { }
      {{- with $dataplane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $dataplane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $dataplane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}